[book]
authors = ["Elara Themica <elara.themica@gmail.com>"]
language = "en"
multilingual = false
src = "src"
title = "GLIFS Contributor Guide"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
